### PR TITLE
fix deprecation warnings

### PR DESCRIPTION
**Pull request by alexciesielski**
Had to update `ncc` due to getting `error:03000086:digital envelope routines::initialization error`.

Also runs `npm run all` since seemingly the `dist` folder still has the old/deprecated `set-output` API calls which results in deprecation warnings when running the action

### CODE REVIEW

**Comment by mattthaber** [comment]
the set-output needs to be addressed asap considering its gone May 31st.

**Comment by kimlep01** [comment]
@joerick could you please review Alex's PR?

**Comment by joerick** [comment]
My apologies, yes will do when I get to a computer

**Comment by joerick** [comment]
Many thanks

**Pull request merged**
